version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e4r
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tech-ensemble-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - tech-ensemble-network

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka
    platform: linux/amd64
    ports:
      - "9092:9092"
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:29093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    networks:
      - tech-ensemble-network

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    platform: linux/amd64
    ports:
      - "9090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: tech-ensemble
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - tech-ensemble-network

  tech-ensemble-vertx-server:
    image: tech-ensemble-vertx-server:latest
    platform: linux/amd64
    #    container_name: tech-ensemble-vertx-server
    ports:
      - "7000:7000"
    networks:
      - tech-ensemble-network

  tech-ensemble-log-db:
    image: tech-ensemble-log-db:latest
    platform: linux/amd64
    #    container_name: tech-ensemble-log-db
    ports:
      - "7001:7001"
    networks:
      - tech-ensemble-network

  tech-ensemble-websocket:
    image: tech-ensemble-websocket:latest
    platform: linux/amd64
    #    container_name: tech-ensemble-websocket
    ports:
      - "7002:7002"
    networks:
      - tech-ensemble-network

volumes:
  postgres_data:
    driver: local

networks:
  tech-ensemble-network:
    driver: bridge