version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"      # 컨테이너 내부에서 접근하는 포트
      - "29092:29092"    # 로컬에서 접근할 때 사용
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://host.docker.internal:29092  # 로컬에서 접근 가능한 호스트 추가
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  tech-ensemble-vertx-server:
    build: .
    container_name: tech-ensemble-vertx-server
    ports:
      - "1234:1234"
    environment:
      KAFKA_BROKER: host.docker.internal:29092  # 로컬에서 카프카 접근을 위해 외부 호스트를 사용
    depends_on:
      - kafka
